version: 1.2
workflows:
   - name: imputation_server_submit
     subclass: WDL
     primaryDescriptorPath: /imputation_server_submit.wdl
     testParameterFiles:
         - /imputation_server_submit.json
   - name: imputation_server_results
     subclass: WDL
     primaryDescriptorPath: /imputation_server_results.wdl
     testParameterFiles:
         - /imputation_server_results.json
         