version: 1.2
workflows:
   - name: imputation_server_submit
     subclass: WDL
     primaryDescriptorPath: /imputation_server_submit.wdl
     testParameterFiles:
         - /imputation_server_submit.json
   - name: imputation_server_results
     subclass: WDL
     primaryDescriptorPath: /imputation_server_results.wdl
     testParameterFiles:
         - /imputation_server_results.json
   - name: chrom_split
     subclass: WDL
     primaryDescriptorPath: /split_by_chrom.wdl
     testParameterFiles:
         - /split_by_chrom.json
   - name: imputed_data_model
     subclass: WDL
     primaryDescriptorPath: /imputed_data_model.wdl
         